import * as cheerio from 'cheerio';
import { X509Certificate } from 'crypto';
import { writeFile } from 'node:fs/promises';

// URL base do repositório SERPRO ou variável de ambiente
const BASE_URL = process.env.SERPRO_DIRECTORY || 'https://repositorio.serpro.gov.br/docs/';

// Busca o conteúdo HTML da página do repositório
async function getRepositoryPage(url: string): Promise<string> {
    console.log(`Fetching repository page: ${url}`);
    const response = await fetch(url);

    if (!response.ok) {
        throw new Error(`Failed to fetch the repository page: ${response.statusText}`);
    }

    console.log(`Repository page fetched successfully`);
    return response.text();
}

// Extrai todos os links de href das linhas da tabela
function getTableUrls(html: string): string[] {
    console.log(`Extracting URLs from HTML table`);
    const $ = cheerio.load(html);
    const urls: string[] = [];

    $('table tr').each((index, element) => {
        const link = $(element).find('a').attr('href');
        if (link) {
            urls.push(link);
        }
    });

    console.log(`${urls.length} URLs found in table`);
    return urls;
}

// Filtra URLs relativas/absolutas e valida padrão de certificado ICP-Brasil
function filterUrls(urls: string[], baseUrl: string): string[] {
    console.log(`Filtering URLs for ICP-Brasil certificates...`);
    const filteredUrls = urls
        .map((url) => {
            try {
                // Resolve URLs relativas para absolutas usando a baseUrl
                return new URL(url, baseUrl).toString();
            } catch {
                return null;
            }
        })
        .filter((resolvedUrl): resolvedUrl is string => resolvedUrl !== null)
        // Filtra apenas arquivos que correspondem ao padrão de certificado ICP-Brasil
        .filter((resolvedUrl) => /icpbrasil(?:v\d+)?\.crt/.test(resolvedUrl));

    console.log(`${filteredUrls.length} ICP-Brasil certificate URLs found`);
    return filteredUrls;
}

// Helper simples para ler um parâmetro da linha de comando e seu valor seguinte
function getArgValue(param: string): { exists: boolean; value?: string } {
    const args = process.argv.slice(2);
    const index = args.indexOf(param);

    if (index === -1) {
        return { exists: false };
    }

    return {
        exists: true,
        value: args[index + 1],
    };
}

// Interface com as informações validadas do certificado
interface CertificateInfo {
    isValid: boolean;        // Indica se o certificado está válido na data atual
    subject: string;         // Assunto/identificação do certificado
    validFrom: string;       // Data inicial de validade (ISO format)
    validTo: string;         // Data final de validade (ISO format)
    fingerprint: string;     // Fingerprint SHA-1 do certificado
    url?: string;            // URL de origem do certificado
    filename?: string;       // Nome do arquivo do certificado
}

// Valida o certificado PEM e extrai informações
function validateCertificate(pem: string): CertificateInfo {
    try {
        console.log(`Validating certificate...`);
        const certificate = new X509Certificate(pem);
        const now = new Date();
        const validFrom = new Date(certificate.validFrom);
        const validTo = new Date(certificate.validTo);
        // Verifica se a data atual está entre validFrom e validTo
        const isValid = now >= validFrom && now <= validTo;

        console.log(`Certificate validated - Subject: ${certificate.subject}`);
        return {
            isValid,
            subject: certificate.subject,
            validFrom: validFrom.toISOString(),
            validTo: validTo.toISOString(),
            fingerprint: certificate.fingerprint,
        };
    } catch (error) {
        console.error('Error validating certificate:', error);
        return {
            isValid: false,
            subject: 'Unknown',
            validFrom: '',
            validTo: '',
            fingerprint: '',
        };
    }
}

// Salva certificados válidos em um arquivo PEM com comentários antes de cada cert
async function saveCertificates(
    certificates: { cert: string; info: CertificateInfo }[],
    targetFile = 'ca-icp-brasil.pem'
): Promise<void> {
    console.log(`\nSaving ${certificates.length} valid certificate(s) to ${targetFile}`);

    const header = [
        '# Serpro PEM bundle',
        '# Generated by script',
        `# Total valid certificates: ${certificates.length}`,
        `# Generated: ${new Date().toISOString()}`,
        '',
    ].join('\n');

    const body = certificates
        .map(({ cert, info }, index) => {
            const comments = [
                `# Certificate ${index + 1}`,
                `# Subject: ${info.subject}`,
                `# Fingerprint: ${info.fingerprint}`,
                `# Valid From: ${info.validFrom}`,
                `# Valid Until: ${info.validTo}`,
                info.url ? `# URL: ${info.url}` : '',
                info.filename ? `# Filename: ${info.filename}` : '',
                '',
            ]
                .filter(Boolean)
                .join('\n');

            return `${comments}\n${cert.trim()}\n`;
        })
        .join('\n');

    await writeFile(targetFile, `${header}${body}`, 'utf8');
    console.log(`File saved: ${targetFile}`);
}

// Salva informações dos certificados em um arquivo JSON
async function saveResultsJson(
    certificates: { cert: string; info: CertificateInfo }[],
    resultFile = 'result.json'
): Promise<void> {
    const results = {
        timestamp: new Date().toISOString(),
        totalCertificates: certificates.length,
        certificates: certificates.map(({ info }) => ({
            subject: info.subject,
            fingerprint: info.fingerprint,
            validFrom: info.validFrom,
            validTo: info.validTo,
            url: info.url || null,
            filename: info.filename || null,
        })),
    };

    await writeFile(resultFile, JSON.stringify(results, null, 2), 'utf8');
    console.log(`Results saved: ${resultFile}`);
}

// Download e validação do arquivo de certificado
async function downloadFile(url: string): Promise<string> {
    console.log(`Downloading certificate from: ${url}`);
    const _response = await fetch(url);

    if (!_response.ok) {
        throw new Error(`Failed to download file from ${url}: ${_response.statusText}`);
    }

    if(!_response.body) {
        throw new Error(`No response body found for ${url}`);
    }

    // Valida o tipo de conteúdo
    const contentType = _response.headers.get('content-type');
    if (contentType !== 'application/x-x509-ca-cert') {
        throw new Error(`Unexpected content type for ${url}: ${contentType}`);
    }

    let _pem = await _response.text();

    // Verifica se o conteúdo é um certificado PEM válido (BEGIN/END CERTIFICATE)
    const certificateRegex = /^-----BEGIN CERTIFICATE-----[\s\n]*[A-Za-z0-9+/=\s\n]*[\s\n]*-----END CERTIFICATE-----\s*$/;
    if (!certificateRegex.test(_pem)) {
        throw new Error(`Invalid certificate format for ${url}`);
    }

    console.log(`Certificate downloaded and validated successfully`);
    return _pem;
}
// Função principal que orquestra todo o processo
async function main() {
    try {
        console.log(`\n${'='.repeat(60)}`);
        console.log(`Starting ICP-Brasil certificate processing`);
        console.log(`${'='.repeat(60)}\n`);

        // Passo 1: Obter página do repositório
        console.log(`[1/5] Fetching repository page...`);
        const pageContent = await getRepositoryPage(BASE_URL);

        // Passo 2: Extrair URLs da tabela
        console.log(`\n[2/4] Extracting URLs...`);
        const tableUrls = getTableUrls(pageContent);

        // Passo 3: Filtrar URLs de certificados válidos
        console.log(`\n[3/4] Filtering ICP-Brasil certificates...`);
        const filteredUrls = filterUrls(tableUrls, BASE_URL);

        if (filteredUrls.length === 0) {
            console.warn(`No ICP-Brasil certificates found`);
            return;
        }

        // Passo 4: Processar cada certificado
        console.log(`\n[4/4] Processing ${filteredUrls.length} certificate(s)...\n`);
        let certificates: {cert: string, info: CertificateInfo}[] = [];
        let processedCount = 0;

        for (const url of filteredUrls) {
            try {
                processedCount++;
                console.log(`\nCertificate ${processedCount}/${filteredUrls.length}`);
                console.log(`${'─'.repeat(60)}`);
                console.log(`Processing URL: ${url}`);

                const pem = await downloadFile(url);
                const filename = url.split('/').pop() || 'unknown';
                const certInfo = validateCertificate(pem);
                certInfo.url = url;
                certInfo.filename = filename;

                if (!certInfo.isValid) {
                    console.log(`Certificate is expired or not valid, skipping push`);
                    continue;
                }

                certificates.push({ cert: pem, info: certInfo });
            } 
            catch (error) {
                console.error(`\nError processing URL ${url}:`, error);
            }
        }

        if (certificates.length > 0) {
            const outfileArg = getArgValue('--outfile');
            const outputFile = outfileArg.value || 'ca-icp-brasil.pem';

            console.log(`\n[5/5] Saving valid certificates to PEM file: ${outputFile}`);
            await saveCertificates(certificates, outputFile);

            const nologArg = getArgValue('--nolog');
            if (!nologArg.exists) {
                const logfileArg = getArgValue('--logfile');
                const logfile = logfileArg.value || 'result.json';
                await saveResultsJson(certificates, logfile);
            }
        } else {
            console.log(`No valid certificates to save`);
        }

        console.log(`\n${'='.repeat(60)}`);
        console.log(`Processing completed - ${certificates.length} certificate(s) processed`);
        console.log(`${'='.repeat(60)}\n`);
    } catch (error) {
        console.error(`\n${'='.repeat(60)}`);
        console.error(`Error in main function:`, error);
        console.error(`${'='.repeat(60)}\n`);
    }
}

main();